language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
     - "~/.platformio"

install:
  - pip install -U platformio

script:
  - rm -rf lib/Adafruit-GFX/{Fonts,fontconvert}
  - platformio run -e $PLATFORMIO_ENV

env:
  - PLATFORMIO_BUILD_FLAGS="-DTRANSPONDER" PLATFORMIO_ENV=nano
  - PLATFORMIO_BUILD_FLAGS="-DHANDSET" PLATFORMIO_ENV=mega
