language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
     - "~/.platformio"

install:
  - pip install -U platformio

script:
  - rm -rf lib/Adafruit-GFX/{Fonts,fontconvert}
  - platformio run -e uno
  - platformio run -e nano
  - platformio run -e mega

env:
  - PLATFORMIO_BUILD_FLAGS="-DTRANSMITTER"
  - PLATFORMIO_BUILD_FLAGS="-DRECEIVER"
