language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
     - "~/.platformio"

install:
  - pip install -U platformio

script:
  - rm -rf lib/Adafruit-GFX/{Fonts,fontconvert} && platformio ci --board=uno --board=nanoatmega328 --board=megaatmega2560

env:
  - PLATFORMIO_BUILD_FLAGS="-DTRANSMITTER"
  - PLATFORMIO_BUILD_FLAGS="-DRECEIVER"
